### ISSUE TITLE
GDG DevFest Logo in <app-header>

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#82] opened 2017-09-10 12:23 UTC
### Description
GDG DevFest logo is shown

### Expected outcome

GDG DevFest logo is hidden if the GDG DevFest logo in <devfest-landing-page> then shows when window is scrolled and the GDG DevFest logo in <devfest-landing-page> is hidden from the page.

### Actual outcome

GDG DevFest logo in <app-header> is visible every time.

### Live Demo
![peek 2017-09-10 20-21](https://user-images.githubusercontent.com/13174418/30249056-b8a0849c-9665-11e7-9bfa-8e1052371c1f.gif)

### Steps to reproduce

1. Your call. 

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [ x] Safari 7
- [ x] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment] 2017-09-10 12:45
Duplicate of #3 

Will fix this on next release

**Comment by juvarabrera** [comment] 2017-09-10 13:08
Thanks

**Comment by jkga** [comment] 2017-09-20 13:02
GDG logo stays visible in mobile browser.

**Comment by tjmonsi** [comment] 2017-09-21 00:15
@jkga can you at least show us a picture so that we will get the issue instantly? Thanks

And like what mobile browser? Because on my mobile browser it works.

**Comment by jkga** [comment] 2017-09-21 00:36
![devfestApp](https://media.giphy.com/media/3o7aD2eGH35N6sKhyM/giphy.gif)
That is from GDG FB post and thats what happens in my device using both "installed app" and mobile browser

Chrome : 57.0.2987.108
Android : 5.1

**Comment by tjmonsi** [comment] 2017-09-21 01:07
Ok will check up on it thanks

**Closed as completed** 2018-03-27 11:23 UTC
Labels: bug, duplicate, enhancement, help wanted, Priority Low
